branch: true
ignore-not-existing: true
llvm: true
filter: covered
output-type: xml
output-path: ./test_results/tr.xml
prefix-dir: ./
ignore:
  - "/*"
  - "C:/*"
  - "../*"
path-mapping:
  - "/path1"
  - "/path2"